apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      publicKeyName: uswest-test
 
